var/www/blueprints/ail_2_ail_sync.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
'''

import os
import sys
import json

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response, make_response
from flask_login import login_required

sys.path.append('modules')
import Flask_config

# Import Role_Manager
from Role_Manager import login_admin, login_read_only

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from core import ail_2_ail
from lib import item_basic
from lib import Tag
from lib import Tracker


bootstrap_label = Flask_config.bootstrap_label

# ============ BLUEPRINT ============
ail_2_ail_sync = Blueprint('ail_2_ail_sync', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/ail_2_ail'))

# ============ VARIABLES ============


# ============ FUNCTIONS ============
def api_validator(api_response):
    if api_response:
        return Response(json.dumps(api_response[0], indent=2, sort_keys=True), mimetype='application/json'), api_response[1]

def create_json_response(data, status_code):
    return Response(json.dumps(data, indent=2, sort_keys=True), mimetype='application/json'), status_code

# ============= ROUTES ==============

@ail_2_ail_sync.route('/settings/ail_2_ail', methods=['GET'])
@login_required
@login_admin
def ail_2_ail_dashboard():
    ail_uuid = ail_2_ail.get_ail_uuid()
    l_servers = ail_2_ail.get_all_running_sync_servers()
    l_servers = ail_2_ail.get_ail_instances_metadata(l_servers, server_sync_mode= True)
    l_clients = ail_2_ail.get_server_all_connected_clients()
    l_clients = ail_2_ail.get_ail_instances_metadata(l_clients, sync_queues=False, client_sync_mode=True)
    return render_template("ail_2_ail_dashboard.html", ail_uuid=ail_uuid,
                                l_servers=l_servers,
                                l_clients=l_clients)

######################
#                    #
#### AIL INSTANCE ####

# # TODO: add more metadata => queues + connections
@ail_2_ail_sync.route('/settings/ail_2_ail/servers', methods=['GET'])
@login_required
@login_admin
def ail_servers():
    l_servers = ail_2_ail.get_all_ail_instances_metadata()
    return render_template("ail_servers.html", l_servers=l_servers)

@ail_2_ail_sync.route('/settings/ail_2_ail/server/view', methods=['GET'])
@login_required
@login_admin
def ail_server_view():
    ail_uuid = request.args.get('uuid')
    server_metadata = ail_2_ail.get_ail_instance_metadata(ail_uuid, client_sync_mode=True, server_sync_mode=True, sync_queues=True)
    server_metadata['sync_queues'] = ail_2_ail.get_queues_metadata(server_metadata['sync_queues'])

    return render_template("view_ail_server.html", server_metadata=server_metadata,
                                bootstrap_label=bootstrap_label)

@ail_2_ail_sync.route('/settings/ail_2_ail/server/api/ping', methods=['GET'])
@login_required
@login_admin
def ail_server_api_ping():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_ping_remote_ail_server(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_server_view', uuid=ail_uuid))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/api/version', methods=['GET'])
@login_required
@login_admin
def ail_server_api_version():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_get_remote_ail_server_version(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_server_view', uuid=ail_uuid))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/client/kill', methods=['GET'])
@login_required
@login_admin
def ail_server_client_kill():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_kill_server_connected_clients(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_2_ail_dashboard'))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/sync_client/kill', methods=['GET'])
@login_required
@login_admin
def ail_server_sync_client_kill():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_kill_sync_client(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_2_ail_dashboard'))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/sync_client/relaunch', methods=['GET'])
@login_required
@login_admin
def ail_server_sync_client_relaunch():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_relaunch_sync_client(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_2_ail_dashboard'))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/sync_client/launch', methods=['GET'])
@login_required
@login_admin
def ail_server_sync_client_launch():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_launch_sync_client(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_2_ail_dashboard'))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/add', methods=['GET', 'POST'])
@login_required
@login_admin
def ail_server_add():
    if request.method == 'POST':
        register_key = request.form.get("register_key")
        ail_uuid = request.form.get("ail_uuid")
        url = request.form.get("ail_url")
        description = request.form.get("ail_description")
        pull = request.form.get("ail_pull")
        push = request.form.get("ail_push")

        input_dict = {"uuid": ail_uuid, "url": url,
                        "description": description,
                        "pull": pull, "push": push}

        if register_key:
            input_dict['key'] = request.form.get("ail_key")

        res = ail_2_ail.api_create_ail_instance(input_dict)
        if res[1] != 200:
            return create_json_response(res[0], res[1])

        return redirect(url_for('ail_2_ail_sync.ail_server_view', uuid=res[0]))
    else:

        return render_template("add_ail_server.html")

@ail_2_ail_sync.route('/settings/ail_2_ail/server/edit', methods=['GET', 'POST'])
@login_required
@login_admin
def ail_server_edit():
    ail_uuid = request.args.get('uuid')
    if request.method == 'POST':
        ail_uuid = request.form.get("ail_uuid")
        ail_key = request.form.get("ail_key")
        url = request.form.get("ail_url")
        description = request.form.get("ail_description")
        pull = request.form.get("ail_pull", False)
        push = request.form.get("ail_push", False)
        if pull:
            pull = True
        if push:
            push = True

        input_dict = {"uuid": ail_uuid, "url": url,
                        "description": description,
                        "key": ail_key,
                        "pull": pull, "push": push}
        res = ail_2_ail.api_edit_ail_instance(input_dict)
        return redirect(url_for('ail_2_ail_sync.ail_server_view', uuid=res[0]))
    else:
        server_metadata = ail_2_ail.get_ail_instance_metadata(ail_uuid)
        return render_template("edit_ail_server.html", server_metadata=server_metadata)


@ail_2_ail_sync.route('/settings/ail_2_ail/server/delete', methods=['GET'])
@login_required
@login_admin
def ail_server_delete():
    ail_uuid = request.args.get('uuid')
    input_dict = {"uuid": ail_uuid}
    res = ail_2_ail.api_delete_ail_instance(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_servers'))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/sync_queues', methods=['GET'])
@login_required
@login_admin
def ail_server_sync_queues():
    ail_uuid = request.args.get('uuid')
    sync_queues = ail_2_ail.get_all_unregistred_queue_by_ail_instance(ail_uuid)
    sync_queues = ail_2_ail.get_queues_metadata(sync_queues)

    return render_template("register_queue.html", bootstrap_label=bootstrap_label,
                                ail_uuid=ail_uuid, sync_queues=sync_queues)

@ail_2_ail_sync.route('/settings/ail_2_ail/server/sync_queues/register', methods=['GET'])
@login_required
@login_admin
def ail_server_sync_queues_register():

    ail_uuid = request.args.get('ail_uuid')
    queue_uuid = request.args.get('queue_uuid')
    input_dict = {"ail_uuid": ail_uuid, "queue_uuid": queue_uuid}
    res = ail_2_ail.api_register_ail_to_sync_queue(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_server_view', uuid=ail_uuid))

@ail_2_ail_sync.route('/settings/ail_2_ail/server/sync_queues/unregister', methods=['GET'])
@login_required
@login_admin
def ail_server_sync_queues_unregister():

    ail_uuid = request.args.get('ail_uuid')
    queue_uuid = request.args.get('queue_uuid')
    input_dict = {"ail_uuid": ail_uuid, "queue_uuid": queue_uuid}
    res = ail_2_ail.api_unregister_ail_to_sync_queue(input_dict)
    if res[1] != 200:
        return create_json_response(res[0], res[1])
    return redirect(url_for('ail_2_ail_sync.ail_server_view', uuid=ail_uuid))

####################
#                  #
#### SYNC QUEUE ####

@ail_2_ail_sync.route('/settings/ail_2_ail/sync_queues', methods=['GET'])
@login_required
@login_admin
def sync_queues():
    ail_uuid = request.args.get('ail_uuid')
    l_queues = ail_2_ail.get_all_queues_metadata()
    return render_template("sync_queues.html", bootstrap_label=bootstrap_label,
                                ail_uuid=ail_uuid, l_queues=l_queues)

var/www/templates/ail_2_ail/ail_2_ail_dashboard.html
<!DOCTYPE html>

<html>
<head>
	<title>AIL-SYNC</title>
	<link rel="icon" href="{{ url_for('static', filename='image/ail-icon.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap4.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap4.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

	<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>

</head>

<body>

	{% include 'nav_bar.html' %}

	<div class="container-fluid">
		<div class="row">

			{% include 'settings/menu_sidebar.html' %}

			<div class="col-12 col-lg-10" id="core_content">

				<div class="d-flex justify-content-center my-4">
					<div class="input-group mb-2 mr-sm-2" style="max-width: 30rem;">
						<div class="input-group-prepend">
							<div class="input-group-text bg-dark text-white">
								<b>AIL UUID</b>
							</div>
						</div>
						<div class="form-control">
							{{ ail_uuid }}
							<input id="ail_uuid" name="ail_uuid" type="text" value="{{ ail_uuid }}" hidden>
						</div>
						<div class="input-group-append">
							<button type="button" class="btn btn-secondary" onclick="copy_ail_uuid()">
								<i class="fas fa-clipboard"></i>
							</button>
						</div>
					</div>

				</div>


				<h1>Connected - AIL Sync:</h3>

				<table id="table_servers" class="table table-striped border-primary">
          <thead class="bg-dark text-white">
            <tr>
                <th>uuid</th>
                <th>url</th>
                <th>description</th>
                <th>sync queues</th>
								<th>sync mode</th>
								<th></th>
            </tr>
          </thead>
          <tbody style="font-size: 15px;">
            {% for dict_server in l_servers %}
              <tr class="border-color: blue;">
                <td>
									<a href="{{ url_for('ail_2_ail_sync.ail_server_view') }}?uuid={{ dict_server['uuid'] }}">
										{{ dict_server['uuid']}}
									</a>
								</td>
                <td>{{ dict_server['url']}}</td>
                <td>{{ dict_server['description']}}</td>
                <td class="text-center">
									{% for queue_uuid in dict_server['sync_queues'] %}
                  	<a href="{{ url_for('ail_2_ail_sync.sync_queue_view') }}?uuid={{queue_uuid}}">
                      {{queue_uuid}}</br>
                    </a>
                  {% endfor %}
                </td>
								<td>
									{% if dict_server['server_sync_mode']['api'] %}
                  	API
                  {% endif %}
									{% if dict_server['server_sync_mode']['pull'] %}
                  	PULL
                  {% endif %}
									{% if dict_server['server_sync_mode']['push'] %}
                  	PUSH
                  {% endif %}
								</td>
								<td>
									{% if dict_server['server_sync_mode']['push'] %}
										<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_client_kill') }}?uuid={{ dict_server['uuid'] }}">
											<button type="button" class="btn btn-danger px-1 py-0">
												<i class="fas fa-times"></i> kill
											</button>
											<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_client_relaunch') }}?uuid={{ dict_server['uuid'] }}">
												<button type="button" class="btn btn-info px-1 py-0">
													<i class="fas fa-redo-alt"></i> reLaunch
												</button>
											</a>
										</a>
                  {% endif %}
								</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>


				<h1>Connected - Remote Sync:</h3>

				<table id="table_servers" class="table table-striped border-primary">
          <thead class="bg-dark text-white">
            <tr>
                <th>uuid</th>
                <th>url</th>
                <th>description</th>
                <th>sync mode</th>
								<th></th>
            </tr>
          </thead>
          <tbody style="font-size: 15px;">
            {% for dict_server in l_clients %}
              <tr class="border-color: blue;">
                <td>
									<a href="{{ url_for('ail_2_ail_sync.ail_server_view') }}?uuid={{ dict_server['uuid'] }}">
										{{ dict_server['uuid']}}
									</a>
								</td>
                <td>{{ dict_server['url']}}</td>
                <td>{{ dict_server['description']}}</td>
                <td class="text-center">
									{% if dict_server['client_sync_mode']['api'] %}
                  	API
                  {% endif %}
									{% if dict_server['client_sync_mode']['pull'] %}
                  	PULL
                  {% endif %}
									{% if dict_server['client_sync_mode']['push'] %}
                  	PUSH
                  {% endif %}
                </td>
								 <td>
									 <a href="{{ url_for('ail_2_ail_sync.ail_server_client_kill') }}?uuid={{ dict_server['uuid'] }}">
										 <button type="button" class="btn btn-danger px-1 py-0">
											 <i class="fas fa-times"></i> kill
										 </button>
									 </a>
								 </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

			</div>

		</div>
	</div>

</body>

<script>
$(document).ready(function(){
	$('#nav_sync').removeClass("text-muted");
	$("#nav_ail_sync").addClass("active");

  $('#table_servers').DataTable({
        "aLengthMenu": [[5, 10, 15, -1], [5, 10, 15, "All"]],
        "iDisplayLength": 10,
        "order": [[ 1, "desc" ]]
  });

});

function copy_ail_uuid() {
	ail_uuid = $('#ail_uuid').val();
	navigator.clipboard.writeText(ail_uuid);
}

function toggle_sidebar(){
	if($('#nav_menu').is(':visible')){
		$('#nav_menu').hide();
		$('#side_menu').removeClass('border-right')
		$('#side_menu').removeClass('col-lg-2')
		$('#core_content').removeClass('col-lg-10')
	}else{
		$('#nav_menu').show();
		$('#side_menu').addClass('border-right')
		$('#side_menu').addClass('col-lg-2')
		$('#core_content').addClass('col-lg-10')
	}
}

</script>

var/www/templates/ail_2_ail/view_ail_server.html
<!DOCTYPE html>

<html>
<head>
	<title>AIL-Framework</title>
	<link rel="icon" href="{{ url_for('static', filename='image/ail-icon.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap4.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap4.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

</head>

<body>

	{% include 'nav_bar.html' %}

	<div class="container-fluid">
		<div class="row">

			{% include 'settings/menu_sidebar.html' %}

			<div class="col-12 col-lg-10" id="core_content">

				<div class="card">
					<div class="card-header bg-dark text-white">
						<span class="badge badge-pill badge-light flex-row-reverse float-right">
							{% if server_metadata['ping'] %}
								<div style="color:Green;">
									<i class="fas fa-check-circle fa-2x"></i>
									PING
								</div>
							{% else %}
								<div style="color:Red;">
									<i class="fas fa-times-circle fa-2x"></i>
									ERROR
								</div>
							{% endif %}
						</span>
						<h5 class="card-title">{{server_metadata['uuid']}}</h5>
					</div>
					<div class="card-body">
						<table class="table table-borderless">
							<tbody>
								<tr>
									<td class="text-right"><b>URL</b></td>
									<td>
										{{server_metadata['url']}}
										{% if server_metadata['ping'] %}
											<span style="color:Green;">
												<i class="fas fa-check-circle"></i>
											</span>
										{% else %}
											<span style="color:Red;">
												<i class="fas fa-times-circle"></i>
											</span>
										{% endif %}
										<div>
											<a href="{{ url_for('ail_2_ail_sync.ail_server_api_ping') }}?uuid={{server_metadata['uuid']}}">
												<button type="button" class="btn btn-primary px-1 py-0">
													<i class="fas fa-redo-alt"></i> ping
												</button>
											</a>
										</div>
									</td>
								</tr>
								<tr>
									<td class="text-right"><b>Api Key</b></td>
									<td>
										{{server_metadata['api_key']}}
										<input id="api_key" name="api_key" type="text" value="{{ server_metadata['api_key'] }}" hidden>
										<button type="button" class="btn btn-secondary px-2 py-0" onclick="copy_api_key()">
											<i class="fas fa-clipboard"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="text-right"><b>Description</b></td>
									<td>
										{{server_metadata['description']}}
									</td>
								</tr>
								<!-- <tr>
									<td class="text-right"><b>Pull</b></td>
									<td>
										{% if server_metadata['pull'] %}
											<span style="color:Green;">
												<i class="fas fa-check-circle"></i> Enabled
											</span>
										{% else %}
											<span class="text-secondary">
												<i class="fas fa-times-circle"></i> Disabled
											</span>
										{% endif %}
									</td>
								</tr> -->
								<tr>
									<td class="text-right"><b>Push</b></td>
									<td>
										{% if server_metadata['push'] %}
											<span style="color:Green;">
												<i class="fas fa-check-circle"></i> Enabled
											</span>
										{% else %}
											<span class="text-secondary">
												<i class="fas fa-times-circle"></i> Disabled
											</span>
										{% endif %}
									</td>
								</tr>
								<tr>
									<td class="text-right"><b>Version</b></td>
									<td>
										{{server_metadata['version']}}
										<a href="{{ url_for('ail_2_ail_sync.ail_server_api_version') }}?uuid={{server_metadata['uuid']}}">
											<button type="button" class="btn btn-info px-1 py-0">
												<i class="fas fa-redo-alt"></i>
											</button>
										</a>
									</td>
								</tr>
								<tr>
									<td class="text-right"><b>AIL Sync</b></td>
									<td>
										{% if server_metadata['server_sync_mode']['api'] %}
	                  	API
	                  {% endif %}
										{% if server_metadata['server_sync_mode']['pull'] %}
	                  	PULL
	                  {% endif %}
										{% if server_metadata['server_sync_mode']['push'] %}
	                  	PUSH

											<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_client_kill') }}?uuid={{ server_metadata['uuid'] }}">
												<button type="button" class="btn btn-danger px-1 py-0">
													<i class="fas fa-times"></i> Kill
												</button>
											</a>
											<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_client_relaunch') }}?uuid={{ server_metadata['uuid'] }}">
												<button type="button" class="btn btn-info px-1 py-0">
													<i class="fas fa-redo-alt"></i> reLaunch
												</button>
											</a>
										{% else %}
											{% if (server_metadata['pull'] or server_metadata['push']) and server_metadata['sync_queues']%}
												<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_client_launch') }}?uuid={{ server_metadata['uuid'] }}">
													<button type="button" class="btn btn-primary px-1 py-0">
														<i class="fas fa-play"></i> Launch
													</button>
												</a>
											{% endif %}
	                  {% endif %}
									</td>
								</tr>
								<tr>
									<td class="text-right"><b>Remote Sync</b></td>
									<td>
										{% if server_metadata['client_sync_mode']['api'] %}
	                  	API
	                  {% endif %}
										{% if server_metadata['client_sync_mode']['pull'] %}
	                  	PULL
	                  {% endif %}
										{% if server_metadata['client_sync_mode']['push'] %}
	                  	PUSH
	                  {% endif %}

										{% if server_metadata['client_sync_mode']['api'] or server_metadata['client_sync_mode']['pull'] or server_metadata['client_sync_mode']['push'] %}
											<a href="{{ url_for('ail_2_ail_sync.ail_server_client_kill') }}?uuid={{ server_metadata['uuid'] }}">
		 										 <button type="button" class="btn btn-danger px-1 py-0">
		 											 <i class="fas fa-times"></i> kill
		 										 </button>
		 									 </a>
									 	{% endif %}
									</td>
								</tr>
							</tbody>
						</table>

						{% if server_metadata['error']%}
<pre class="bg-dark text-white">
					----------------------------
					-          ERROR           -
					----------------------------
{{server_metadata['error']}}
</pre>
						{% endif %}

						<div class="my-4">
							<a href="{{ url_for('ail_2_ail_sync.ail_server_delete') }}?uuid={{server_metadata['uuid']}}">
								<button type="button" class="btn btn-danger">
									<i class="fas fa-trash-alt"></i> <b>Delete AIL Server</b>
								</button>
							</a>
							<a href="{{ url_for('ail_2_ail_sync.ail_server_edit') }}?uuid={{server_metadata['uuid']}}">
								<button type="button" class="btn btn-info">
									<i class="fas fa-pencil-alt"></i> <b>Edit</b>
								</button>
							</a>
						</div>

						<div class="card">
							<div class="card-header bg-secondary text-white">
								<h6 class="card-title"><b>SYNC QUEUES:</b></h6>
							</div>
							<div class="card-body">

								<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_queues') }}?uuid={{ server_metadata['uuid'] }}">
									<button type="button" class="btn btn-primary my-4">
										<i class="fas fa-plus"></i> <b>Register Sync Queue</b>
									</button>
								</a>

								<table id="table_sync_queues" class="table table-striped border-primary">
				          <thead class="bg-dark text-white">
				            <tr>
												<th>name</th>
				                <th>uuid</th>
				                <th>description</th>
				                <th>max size</th>
												<th>Unregister Queue</th>
				            </tr>
				          </thead>
				          <tbody style="font-size: 15px;">
				            {% for dict_queue in server_metadata['sync_queues'] %}
				              <tr class="border-color: blue;">
												<td>{{ dict_queue['name']}}</td>
				                <td>
													<a href="{{ url_for('ail_2_ail_sync.sync_queue_view') }}?uuid={{ dict_queue['uuid'] }}">
														{{ dict_queue['uuid']}}
													</a>
													<div>
														{% for tag in dict_queue['tags'] %}
															<span class="badge badge-{{ bootstrap_label[loop.index0 % 5] }} pull-left">{{ tag }}</span>
														{% endfor %}
													</div>
												</td>
				                <td>{{ dict_queue['description']}}</td>
												<td>{{ dict_queue['max_size']}}</td>
												<td class="text-right">
													<a href="{{ url_for('ail_2_ail_sync.ail_server_sync_queues_unregister') }}?ail_uuid={{ server_metadata['uuid'] }}&queue_uuid={{ dict_queue['uuid'] }}">
														<button type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
													</a>
												</td>
				              </tr>
				            {% endfor %}
				          </tbody>
				        </table>


					</div>


				</div>
			</div>


		</div>

	</div>

</body>

<script>
$(document).ready(function(){
	$('#nav_sync').removeClass("text-muted");

  $('#table_sync_queues').DataTable({
        "aLengthMenu": [[5, 10, 15, -1], [5, 10, 15, "All"]],
        "iDisplayLength": 10,
        "order": [[ 0, "asc" ]]
  });

});

function copy_api_key() {
	api_key = $('#api_key').val();
	navigator.clipboard.writeText(api_key);
}

function toggle_sidebar(){
	if($('#nav_menu').is(':visible')){
		$('#nav_menu').hide();
		$('#side_menu').removeClass('border-right')
		$('#side_menu').removeClass('col-lg-2')
		$('#core_content').removeClass('col-lg-10')
	}else{
		$('#nav_menu').show();
		$('#side_menu').addClass('border-right')
		$('#side_menu').addClass('col-lg-2')
		$('#core_content').addClass('col-lg-10')
	}
}

</script>