var/www/blueprints/objects_item.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
'''

import difflib
import os
import sys

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response, abort, send_file, send_from_directory
from flask_login import login_required, current_user

# Import Role_Manager
from Role_Manager import login_admin, login_user, login_read_only, no_cache

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from lib import ConfigLoader
from lib import chats_viewer
from lib import item_basic
from lib.objects.Items import Item
from lib.objects.Screenshots import Screenshot
from lib import Tag

from lib import Investigations
from lib import module_extractor


# ============ BLUEPRINT ============
objects_item = Blueprint('objects_item', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/objects/item'))

# ============ VARIABLES ============
config_loader = ConfigLoader.ConfigLoader()
bootstrap_label = ['primary', 'success', 'danger', 'warning', 'info']
DiffMaxLineLength = config_loader.get_config_int('Flask', 'DiffMaxLineLength')
max_preview_modal = config_loader.get_config_int('Flask', 'max_preview_modal')
SCREENSHOT_FOLDER = ConfigLoader.get_screenshots_dir()
config_loader = None

# ============ FUNCTIONS ============


# ============= ROUTES ==============

@objects_item.route('/screenshot/<path:filename>')
@login_required
@login_read_only
@no_cache
def screenshot(filename):
    if not filename:
        abort(404)
    if not 64 <= len(filename) <= 70:
        abort(404)
    filename = filename.replace('/', '')
    s = Screenshot(filename)
    return send_from_directory(SCREENSHOT_FOLDER, s.get_rel_path(add_extension=True), as_attachment=False, mimetype='image')

@objects_item.route("/object/item")
@login_required
@login_read_only
def showItem():  # # TODO: support post
    user_org = current_user.get_org()
    item_id = request.args.get('id')
    if not item_id or not item_basic.exist_item(item_id):
        abort(404)

    item = Item(item_id)
    meta = item.get_meta(options={'content', 'crawler', 'duplicates', 'file_name', 'investigations', 'lines', 'size'})
    if meta['file_name']:
        message = chats_viewer.api_get_message(item.get_message())
        if message[1] == 200:
            message = message[0]
        else:
            message = None
    else:
        message = None

    meta['name'] = meta['id'].replace('/', ' / ')
    meta['father'] = item_basic.get_item_parent(item_id)
    ## EXPORT SECTION
    # # TODO: ADD in Export SECTION
    # meta['hive_case'] = Export.get_item_hive_cases(item_id)
    meta['hive_case'] = None

    if meta.get('investigations'):
        invests = []
        for investigation_uuid in meta['investigations']:
            inv = Investigations.Investigation(investigation_uuid)
            if not inv.check_level(user_org):
                continue

            invests.append(inv.get_metadata(r_str=True))
        meta['investigations'] = invests
    else:
        meta['investigations'] = []

    extracted = module_extractor.extract(current_user.get_user_id(), 'item', '', item.id, content=meta['content'])
    extracted_matches = module_extractor.get_extracted_by_match(extracted)

    return render_template("show_item.html", bootstrap_label=bootstrap_label,
                           modal_add_tags=Tag.get_modal_add_tags(meta['id'], object_type='item'),
                           is_hive_connected=False,
                           meta=meta, message=message,
                           extracted=extracted, extracted_matches=extracted_matches)

    # kvrocks data

    # # TODO: dynamic load:
    ## duplicates
    ## correlations

    ## Dynamic Path FIX

@objects_item.route("/objects/item/html2text")
@login_required
@login_read_only
def html2text(): # # TODO: support post
    item_id = request.args.get('id')
    if not item_id or not item_basic.exist_item(item_id):
        abort(404)
    item = Item(item_id)
    return item.get_html2text_content()

@objects_item.route("/objects/item/raw_content")
@login_required
@login_read_only
def item_raw_content(): # # TODO: support post
    item_id = request.args.get('id')
    if not item_id or not item_basic.exist_item(item_id):
        abort(404)
    item = Item(item_id)
    return Response(item.get_content(), mimetype='text/plain')

@objects_item.route("/objects/item/download")
@login_required
@login_read_only
def item_download():  # # TODO: support post
    item_id = request.args.get('id')
    if not item_id or not item_basic.exist_item(item_id):
        abort(404)
    item = Item(item_id)
    return send_file(item.get_raw_content(), download_name=item_id, as_attachment=True)

@objects_item.route("/objects/item/content/more")
@login_required
@login_read_only
def item_content_more():
    item_id = request.args.get('id', '')
    item = Item(item_id)
    item_content = item.get_content()
    to_return = item_content[max_preview_modal-1:]
    return to_return

@objects_item.route("/objects/item/diff")
@login_required
@login_user
def object_item_diff():
    id1 = request.args.get('s1', '')
    id2 = request.args.get('s2', '')
    item1 = Item(id1)
    item2 = Item(id2)
    item1_content = item1.get_content()
    item2_content = item2.get_content()
    i1_max_len = item1.get_meta_lines(content=item1_content)['max_length']
    i2_max_len = item2.get_meta_lines(content=item2_content)['max_length']
    if i1_max_len > DiffMaxLineLength or i2_max_len > DiffMaxLineLength:
        return jsonify({'error': "Can't make the difference as the lines are too long."}), 400
    lines1 = item1_content.splitlines()
    lines2 = item2_content.splitlines()
    htmldiff = difflib.HtmlDiff()
    diff = htmldiff.make_file(lines1, lines2)
    return diff

@objects_item.route("/objects/item/preview")
@login_required
@login_read_only
def item_preview():
    item_id = request.args.get('id')
    if not item_id or not item_basic.exist_item(item_id):
        abort(404)

    item = Item(item_id)
    meta = item.get_meta(options={'content', 'crawler', 'lines', 'mimetype', 'parent', 'size'})
    initsize = len(meta['content'])
    if len(meta['content']) > max_preview_modal:
        meta['content'] = meta['content'][0:max_preview_modal]
    meta['nb_correlations'] = item.get_nb_correlations()

    misp_eventid = None  # TODO SHOW MISP EVENT
    misp_url = None  # TODO SHOW MISP EVENT
    hive_caseid = None  # TODO SHOW HIVE CASE
    hive_url = None  # TODO SHOW HIVE CASE

    return render_template("show_item_min.html", bootstrap_label=bootstrap_label,
                           meta=meta, initsize=initsize,

                           misp_eventid=misp_eventid, misp_url=misp_url,
                           hive_caseid=hive_caseid, hive_url=hive_url)

var/www/blueprints/tags_ui.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
'''

import os
import sys

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, abort
from flask_login import login_required

sys.path.append('modules')
import Flask_config

# Import Role_Manager
from Role_Manager import login_admin, login_user_no_api, login_read_only

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from packages import Date
from lib import Tag
from lib.objects import ail_objects

bootstrap_label = Flask_config.bootstrap_label

# ============ BLUEPRINT ============
tags_ui = Blueprint('tags_ui', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/tags'))

# ============ VARIABLES ============



# ============ FUNCTIONS ============


# ============= ROUTES ==============
@tags_ui.route('/tag/taxonomies')
@login_required
@login_read_only
def tags_taxonomies():
    taxonomies = Tag.get_taxonomies_meta()
    return render_template("tags/taxonomies.html", taxonomies=taxonomies)

@tags_ui.route('/tag/taxonomy')
@login_required
@login_read_only
def tags_taxonomy():
    taxonomy_name = request.args.get('taxonomy')
    taxonomy = Tag.get_taxonomy_meta(taxonomy_name, enabled=True, predicates=True, tags=True, enabled_tags=True)
    if not taxonomy:
        abort(404)
    return render_template("tags/taxonomy.html", taxonomy=taxonomy)

@tags_ui.route('/tag/taxonomy/enable')
@login_required
@login_admin
def taxonomy_enable():
    taxonomy = request.args.get('taxonomy')
    res = Tag.api_enable_taxonomy_tags({'taxonomy': taxonomy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/taxonomy/disable')
@login_required
@login_admin
def taxonomy_disable():
    taxonomy = request.args.get('taxonomy')
    res = Tag.api_disable_taxonomy_tags({'taxonomy': taxonomy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/taxonomy/enable_tags')
@login_required
@login_admin
def taxonomy_enable_tags():
    taxonomy = request.args.get('taxonomy')
    tags = request.args.getlist('tags')
    res = Tag.api_update_taxonomy_tag_enabled({'taxonomy': taxonomy, 'tags': tags})
    if res:
        return jsonify(res[0]), 1
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/galaxies')
@login_required
@login_read_only
def tags_galaxies():
    galaxies = Tag.get_galaxies_meta()
    return render_template("tags/galaxies.html", galaxies=galaxies)

@tags_ui.route('/tag/galaxy')
@login_required
@login_read_only
def tags_galaxy():
    galaxy_name = request.args.get('galaxy')
    galaxy = Tag.get_cluster_meta(galaxy_name, enabled=True, tags=True)
    if not galaxy:
        abort(404)
    return render_template("tags/galaxy.html", galaxy=galaxy)

@tags_ui.route('/tag/galaxy/tag')
@login_required
@login_read_only
def tags_galaxy_tag():
    galaxy_type = request.args.get('galaxy')
    tag = request.args.get('tag')
    tag_meta = Tag.get_galaxy_tag_meta(galaxy_type, tag)
    if not tag_meta:
        abort(404)
    return render_template("tags/galaxy_tag.html", galaxy=galaxy_type, tag=tag_meta)

@tags_ui.route('/tag/galaxy/enable')
@login_required
@login_admin
def galaxy_enable():
    galaxy = request.args.get('galaxy')
    res = Tag.api_enable_galaxy_tags({'galaxy': galaxy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))

@tags_ui.route('/tag/galaxy/disable')
@login_required
@login_admin
def galaxy_disable():
    galaxy = request.args.get('galaxy')
    res = Tag.api_disable_galaxy_tags({'galaxy': galaxy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))

@tags_ui.route('/tag/galaxy/enable_tags')
@login_required
@login_admin
def galaxy_enable_tags():
    galaxy = request.args.get('galaxy')
    tags = request.args.getlist('tags')
    res = Tag.api_update_galaxy_tag_enabled({'galaxy': galaxy, 'tags': tags})
    if res:
        return jsonify(res[0]), 1
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))


@tags_ui.route('/tag/enabled')
@login_required
@login_read_only
def get_all_tags_enabled():
    return jsonify(Tag.get_enabled_tags_with_synonyms_ui())

@tags_ui.route('/tag/confirm')
@login_required
@login_user_no_api
def tag_confirm():
    tag = request.args.get('tag')
    obj_type = request.args.get('type')
    subtype = request.args.get('subtype', '')
    obj_id = request.args.get('id', '')
    obj = ail_objects.get_object(obj_type, subtype, obj_id)
    if not obj.exists():
        abort(404)
    Tag.confirm_tag(tag, obj)

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(obj.get_link(flask_context=True))

@tags_ui.route('/tag/add_tags')
@login_required
@login_user_no_api
def add_tags():

    tags = request.args.get('tags')
    tagsgalaxies = request.args.get('tagsgalaxies')
    object_type = request.args.get('type')
    object_subtype = request.args.get('subtype')
    object_id = request.args.get('id')

    list_tag = tags.split(',')
    list_tag_galaxies = tagsgalaxies.split(',')

    res = Tag.api_add_obj_tags(tags=list_tag, galaxy_tags=list_tag_galaxies,
                               object_id=object_id, object_type=object_type, object_subtype=object_subtype)
    # error
    if res[1] != 200:
        return str(res[0])

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(ail_objects.get_object_link(object_type, object_subtype, object_id, flask_context=True))

@tags_ui.route('/tag/delete_tag') # TODO FIX REQUEST PARAMETER
@login_required
@login_user_no_api
def delete_tag():
    object_type = request.args.get('type')
    subtype = request.args.get('subtype', '')
    object_id = request.args.get('id')
    tag = request.args.get('tag')

    res = Tag.api_delete_obj_tags(tags=[tag], object_id=object_id, object_type=object_type, subtype=subtype)
    if res[1] != 200:
        return str(res[0])
    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(ail_objects.get_object_link(object_type, subtype, object_id, flask_context=True))


@tags_ui.route('/tag/get_all_tags')
@login_required
@login_read_only
def get_all_tags():
    return jsonify(Tag.get_all_tags())

@tags_ui.route('/tag/get_taxonomies_customs_tags')
@login_required
@login_read_only
def get_all_taxonomies_customs_tags():
    return jsonify(Tag.get_taxonomies_customs_tags(r_list=True))

@tags_ui.route('/tag/get_all_obj_tags')
@login_required
@login_read_only
def get_all_obj_tags():
    object_type = request.args.get('object_type')
    res = ail_objects.api_sanitize_object_type(object_type)
    if res:
        return jsonify(res[0]), res[1]
    return jsonify(Tag.get_all_obj_tags(object_type))

@tags_ui.route('/tag/taxonomies/tags/enabled/json')
@login_required
@login_read_only
def tag_taxonomies_tags_enabled_json():
    return jsonify(Tag.get_taxonomies_enabled_tags(r_list=True))

@tags_ui.route('/tag/galaxies/tags/enabled/json')
@login_required
@login_read_only
def tag_galaxies_tags_enabled_json():
    tags = Tag.get_galaxies_enabled_tags()
    return jsonify(Tag.get_tags_selector_dict(tags))

@tags_ui.route('/tag/custum/tags/enabled/json')
@login_required
@login_read_only
def tag_custum_tags_enabled_json():
    return jsonify(Tag.get_custom_enabled_tags(r_list=True))

@tags_ui.route('/tag/taxonomie/tags/enabled/json')
@login_required
@login_read_only
def tag_taxonomie_tags_enabled_json():
    taxonomie = request.args.get('taxonomie')
    return jsonify(Tag.get_taxonomie_enabled_tags(taxonomie, r_list=True))

@tags_ui.route('/tag/galaxy/tags/enabled/json')
@login_required
@login_read_only
def tag_galaxy_tags_enabled_json():
    galaxy = request.args.get('galaxy')
    tags = Tag.get_galaxy_enabled_tags(galaxy, r_list=True)
    return jsonify(Tag.get_tags_selector_dict(tags))

@tags_ui.route('/tag/search/item')
@login_required
@login_read_only
def tags_search_items():
    object_type = 'item'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    dict_tagged['date'] = Date.sanitise_date_range('', '', separator='-')
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/message')
@login_required
@login_read_only
def tags_search_messages():
    object_type = 'message'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    dict_tagged['date'] = Date.sanitise_date_range('', '', separator='-')
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/image')
@login_required
@login_read_only
def tags_search_images():
    object_type = 'image'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/ocr')
@login_required
@login_read_only
def tags_search_ocrs():
    object_type = 'ocr'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/qrcode')
@login_required
@login_read_only
def tags_search_qrcodes():
    object_type = 'qrcode'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}

var/www/templates/modals/add_tags.html
<div id="add_tags_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div id="add_tags_modal_content" class="modal-content">
      <div class="modal-header" style="border-bottom: 4px solid #cccccc; background-color: #cccccc; color: #ffffff;">
        <h4>Add New Tags</h4>
      </div>

      <div class="modal-body">

        <div class="input-group" >
          <input id="ltags_add_modal" type="text" class="form-control" autocomplete="off" style="width: 760px">
        </div>

        <div class="dropdown">
          <button type="button" class="btn btn-info dropdown-toggle mt-1 mb-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdown-taxonomie-add-modal">
             Taxonomie Selected
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-taxonomie-add-modal"> <!-- TODO: make dropdown-scrollable -->
            <h6 class="dropdown-header">Taxonomie Tags</h6>
            <button class="dropdown-item" type="button" id="add-modal-all-tags-taxonomies">All Tags <i class="fas fa-tags"></i></button>
            <div class="dropdown-divider"></div>
            {% for taxo in modal_add_tags['active_taxonomies'] %}
                <button class="dropdown-item" type="button" id="add-modal-{{ taxo }}-id{{ loop.index0 }}">{{ taxo }}</button>
            {% endfor %}
          </div>
        </div>

        <div class="input-group">
          <input id="ltagsgalaxies_add_modal" type="text" class="form-control" autocomplete="off" style="width: 760px">
        </div>

        <div class="dropdown">
          <button type="button" class="btn btn-info dropdown-toggle mt-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdown-galaxy-add-modal">
             Galaxy Selected
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-galaxy-add-modal"> <!-- TODO: make dropdown-scrollable -->
            <h6 class="dropdown-header">Galaxy Tags</h6>
            <button class="dropdown-item" type="button" id="add-modal-all-tags-galaxies">All Tags <i class="fas fa-tags"></i></button>
            <div class="dropdown-divider"></div>
            {% for galaxy in modal_add_tags['active_galaxies'] %}
                <button class="dropdown-item" type="button" id="add-modal-{{ galaxy }}-idgalax{{ loop.index0 }}">{{ galaxy }}</button>
            {% endfor %}
          </div>
        </div>

      </div>

      <div class="modal-footer">
        <a class="btn btn-link" href="{{ url_for('tags_ui.tags_taxonomies') }}" target="_blank">
            <span class="label-icon">Taxonomies</span>
            <i class="fas fa-wrench fa-2x"></i>
        </a>
        <a class="btn btn-link" href="{{ url_for('tags_ui.tags_galaxies') }}" target="_blank">
            <span class="label-icon">Galaxies</span>
            <i class="fas fa-rocket fa-2x"></i>
        </a>
        <button class="btn btn-primary" onclick="addTags()">
            <i class="fas fa-plus"></i>
            Add Tags
        </button>
        <button type="button" class="btn btn-default" data-dismiss="modal" >Close</button>

      </div>
    </div>
  </div>
</div>

<script> // TODO: add tags to PASTE or DOMAIN
var ltags_modal_add;
var ltagsgalaxies_modal_add;

$.getJSON("{{ url_for('tags_ui.get_all_taxonomies_customs_tags') }}",
    function(data) {

      ltags_modal_add = $('#ltags_add_modal').tagSuggest({
        data: data,
        maxDropHeight: 200,
        name: 'ltags_modal_add'
      });
    });

$.getJSON("{{ url_for('tags_ui.tag_galaxies_tags_enabled_json') }}",
  function(data) {

    ltagsgalaxies_modal_add = $('#ltagsgalaxies_add_modal').tagSuggest({
      data: data,
      maxDropHeight: 200,
      name: 'ltagsgalaxies_modal_add'
    });
  });

jQuery("#add-modal-all-tags-taxonomies").click(function(e){
        //change input tags list
      $.getJSON("{{ url_for('tags_ui.get_all_taxonomies_customs_tags') }}",
        function(data) {
          ltags_modal_add.setData(data)
      });
    });

jQuery("#add-modal-all-tags-galaxies").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_galaxies_tags_enabled_json') }}",
        function(data) {
          ltagsgalaxies_modal_add.setData(data)
      });
    });

{% for taxo in modal_add_tags['active_taxonomies'] %}
    jQuery("#add-modal-{{ taxo }}-id{{ loop.index0 }}").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_taxonomie_tags_enabled_json') }}?taxonomie={{ taxo }}",
        function(data) {
          ltags_modal_add.setData(data)
  });
});
{% endfor %}

{% for galaxy in modal_add_tags['active_galaxies'] %}
    jQuery("#add-modal-{{ galaxy }}-idgalax{{ loop.index0 }}").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_galaxy_tags_enabled_json') }}?galaxy={{ galaxy }}",
        function(data) {
          ltagsgalaxies_modal_add.setData(data)
  });
});
{% endfor %}

function addTags() {
  var tags = ltags_modal_add.getValue()
  var tagsgalaxy = ltagsgalaxies_modal_add.getValue()
  window.location.replace("{{ url_for('tags_ui.add_tags') }}?tags=" + tags + "&tagsgalaxies=" + tagsgalaxy + "&type={{ modal_add_tags['object_type'] }}&subtype={{ modal_add_tags['object_subtype'] }}&id={{ modal_add_tags['object_id'] }}");
}
</script>

var/www/templates/modals/show_min_item.html
<div id="modal_show_min_item" class="modal fade" role="dialog">
 <div class="modal-dialog modal-lg">

   <!-- Modal content-->
   <div id="modal_show_min_item_content" class="modal-content">
     <div id="modal_show_min_item_body" class="modal-body" max-width="850px">
       <p>Loading item information...</p>
       <img id="loading-gif-modal" src="{{url_for('static', filename='image/loading.gif') }}" height="26" width="26" style="margin: 4px;">
     </div>
     <div class="modal-footer">
       <a id="modal_show_min_item_button_show_item" target="_blank" href=""><button type="button" class="btn btn-info">Show Item</button></a>
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     </div>
   </div>
 </div>
</div>

<script>
// static data
var can_change_modal_content = true;
var alert_message = '<div class="alert alert-info alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><strong>No more data.</strong> Full paste displayed.</div>';
var complete_item = null;
var char_to_display = {%if char_to_display%}{{ char_to_display }}{%else%}800{%endif%};
var start_index = 0;

// Reset modal content
$("#modal_show_min_item").on('hidden.bs.modal', function () {
    can_change_modal_content = true;
    $("#modal_show_min_item_body").html("<p>Loading item information...</p>");
    var loading_gif = "<img id='loading-gif-modal' class='img-center' src=\"{{url_for('static', filename='image/loading.gif') }}\" height='26' width='26' style='margin: 4px;'>";
    $("#modal_show_min_item_body").append(loading_gif); // Show the loading GIF
    $("#modal_show_min_item_button_show_item").attr('href', '');
    $("#modal_show_min_item_button_show_item").hide();
    complete_item = null;
    start_index = 0;
});

// Update the item preview in the modal
function update_preview() {
    if (start_index + char_to_display > complete_item.length-1){ // end of item reached
        var final_index = complete_item.length-1;
        var flag_stop = true;
    } else {
        var final_index = start_index + char_to_display;
    }

    if (final_index != start_index){ // still have data to display
        // Append the new content using text() and not append (XSS)
        $("#modal_show_min_item_body").find("#paste-holder")
                .text($("#modal_show_min_item_body")
                .find("#paste-holder").text() + complete_item.substring(start_index+1, final_index+1));
        start_index = final_index;
        if (flag_stop)
            nothing_to_display();
    } else {
        nothing_to_display();
    }
}

// Update the modal when there is no more data
function nothing_to_display() {
    var new_content = $(alert_message).hide();
    $("#modal_show_min_item_body").find("#panel-body").append(new_content);
    new_content.show('fast');
    $("#load-more-button").hide();
}

function get_html_and_update_modal(event, truemodal) {
    event.preventDefault();

    var modal=truemodal;
    var url = " {{ url_for('objects_item.item_preview')  }}?id=" + modal.attr('data-path');
    $.get(url, function (data) {

        // verify that the reveived data is really the current clicked item. Otherwise, ignore it.
            can_change_modal_content = false;

            // clear data by removing html, body, head tags. prevent dark modal background stack bug.
            var cleared_data = data.split("<body>")[1].split("</body>")[0];
            $("#modal_show_min_item_body").html(cleared_data);

            var button = $('<button type="button" id="load-more-button" class="btn btn-outline-primary rounded-circle px-1 py-0" data-url="' + $(modal).attr('data-path') +'" data-toggle="tooltip" data-placement="bottom" title="Load more content"><i class="fas fa-arrow-circle-down mt-1"></i></button>');
            button.tooltip(button);
            $("#container-show-more").append(button);

            $("#modal_show_min_item_button_show_item").attr('href', '{{ url_for('objects_item.showItem')  }}?id=' + $(modal).attr('data-path'));
            $("#modal_show_min_item_button_show_item").show('fast');
            $("#loading-gif-modal").css("visibility", "hidden"); // Hide the loading GIF
            if ($("[data-initsize]").attr('data-initsize') < char_to_display) { // All the content is displayed
                nothing_to_display();
            }
            // collapse decoded
            $('#collapseDecoded').collapse('hide');
            // On click, donwload all item's content
            $("#load-more-button").on("click", function (event) {
                if (complete_item == null) { //Donwload only once
                    $.get("{{ url_for('objects_item.item_content_more') }}"+"?id="+$(modal).attr('data-path'), function(data, status){
                        complete_item = data;
                        update_preview();
                    });
                } else {
                    update_preview();
                }
            });
    });
}

</script>