var/www/blueprints/tags_ui.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
'''

import os
import sys

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, abort
from flask_login import login_required

sys.path.append('modules')
import Flask_config

# Import Role_Manager
from Role_Manager import login_admin, login_user_no_api, login_read_only

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from packages import Date
from lib import Tag
from lib.objects import ail_objects

bootstrap_label = Flask_config.bootstrap_label

# ============ BLUEPRINT ============
tags_ui = Blueprint('tags_ui', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/tags'))

# ============ VARIABLES ============



# ============ FUNCTIONS ============


# ============= ROUTES ==============
@tags_ui.route('/tag/taxonomies')
@login_required
@login_read_only
def tags_taxonomies():
    taxonomies = Tag.get_taxonomies_meta()
    return render_template("tags/taxonomies.html", taxonomies=taxonomies)

@tags_ui.route('/tag/taxonomy')
@login_required
@login_read_only
def tags_taxonomy():
    taxonomy_name = request.args.get('taxonomy')
    taxonomy = Tag.get_taxonomy_meta(taxonomy_name, enabled=True, predicates=True, tags=True, enabled_tags=True)
    if not taxonomy:
        abort(404)
    return render_template("tags/taxonomy.html", taxonomy=taxonomy)

@tags_ui.route('/tag/taxonomy/enable')
@login_required
@login_admin
def taxonomy_enable():
    taxonomy = request.args.get('taxonomy')
    res = Tag.api_enable_taxonomy_tags({'taxonomy': taxonomy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/taxonomy/disable')
@login_required
@login_admin
def taxonomy_disable():
    taxonomy = request.args.get('taxonomy')
    res = Tag.api_disable_taxonomy_tags({'taxonomy': taxonomy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/taxonomy/enable_tags')
@login_required
@login_admin
def taxonomy_enable_tags():
    taxonomy = request.args.get('taxonomy')
    tags = request.args.getlist('tags')
    res = Tag.api_update_taxonomy_tag_enabled({'taxonomy': taxonomy, 'tags': tags})
    if res:
        return jsonify(res[0]), 1
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/galaxies')
@login_required
@login_read_only
def tags_galaxies():
    galaxies = Tag.get_galaxies_meta()
    return render_template("tags/galaxies.html", galaxies=galaxies)

@tags_ui.route('/tag/galaxy')
@login_required
@login_read_only
def tags_galaxy():
    galaxy_name = request.args.get('galaxy')
    galaxy = Tag.get_cluster_meta(galaxy_name, enabled=True, tags=True)
    if not galaxy:
        abort(404)
    return render_template("tags/galaxy.html", galaxy=galaxy)

@tags_ui.route('/tag/galaxy/tag')
@login_required
@login_read_only
def tags_galaxy_tag():
    galaxy_type = request.args.get('galaxy')
    tag = request.args.get('tag')
    tag_meta = Tag.get_galaxy_tag_meta(galaxy_type, tag)
    if not tag_meta:
        abort(404)
    return render_template("tags/galaxy_tag.html", galaxy=galaxy_type, tag=tag_meta)

@tags_ui.route('/tag/galaxy/enable')
@login_required
@login_admin
def galaxy_enable():
    galaxy = request.args.get('galaxy')
    res = Tag.api_enable_galaxy_tags({'galaxy': galaxy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))

@tags_ui.route('/tag/galaxy/disable')
@login_required
@login_admin
def galaxy_disable():
    galaxy = request.args.get('galaxy')
    res = Tag.api_disable_galaxy_tags({'galaxy': galaxy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))

@tags_ui.route('/tag/galaxy/enable_tags')
@login_required
@login_admin
def galaxy_enable_tags():
    galaxy = request.args.get('galaxy')
    tags = request.args.getlist('tags')
    res = Tag.api_update_galaxy_tag_enabled({'galaxy': galaxy, 'tags': tags})
    if res:
        return jsonify(res[0]), 1
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))


@tags_ui.route('/tag/enabled')
@login_required
@login_read_only
def get_all_tags_enabled():
    return jsonify(Tag.get_enabled_tags_with_synonyms_ui())

@tags_ui.route('/tag/confirm')
@login_required
@login_user_no_api
def tag_confirm():
    tag = request.args.get('tag')
    obj_type = request.args.get('type')
    subtype = request.args.get('subtype', '')
    obj_id = request.args.get('id', '')
    obj = ail_objects.get_object(obj_type, subtype, obj_id)
    if not obj.exists():
        abort(404)
    Tag.confirm_tag(tag, obj)

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(obj.get_link(flask_context=True))

@tags_ui.route('/tag/add_tags')
@login_required
@login_user_no_api
def add_tags():

    tags = request.args.get('tags')
    tagsgalaxies = request.args.get('tagsgalaxies')
    object_type = request.args.get('type')
    object_subtype = request.args.get('subtype')
    object_id = request.args.get('id')

    list_tag = tags.split(',')
    list_tag_galaxies = tagsgalaxies.split(',')

    res = Tag.api_add_obj_tags(tags=list_tag, galaxy_tags=list_tag_galaxies,
                               object_id=object_id, object_type=object_type, object_subtype=object_subtype)
    # error
    if res[1] != 200:
        return str(res[0])

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(ail_objects.get_object_link(object_type, object_subtype, object_id, flask_context=True))

@tags_ui.route('/tag/delete_tag') # TODO FIX REQUEST PARAMETER
@login_required
@login_user_no_api
def delete_tag():
    object_type = request.args.get('type')
    subtype = request.args.get('subtype', '')
    object_id = request.args.get('id')
    tag = request.args.get('tag')

    res = Tag.api_delete_obj_tags(tags=[tag], object_id=object_id, object_type=object_type, subtype=subtype)
    if res[1] != 200:
        return str(res[0])
    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(ail_objects.get_object_link(object_type, subtype, object_id, flask_context=True))


@tags_ui.route('/tag/get_all_tags')
@login_required
@login_read_only
def get_all_tags():
    return jsonify(Tag.get_all_tags())

@tags_ui.route('/tag/get_taxonomies_customs_tags')
@login_required
@login_read_only
def get_all_taxonomies_customs_tags():
    return jsonify(Tag.get_taxonomies_customs_tags(r_list=True))

@tags_ui.route('/tag/get_all_obj_tags')
@login_required
@login_read_only
def get_all_obj_tags():
    object_type = request.args.get('object_type')
    res = ail_objects.api_sanitize_object_type(object_type)
    if res:
        return jsonify(res[0]), res[1]
    return jsonify(Tag.get_all_obj_tags(object_type))

@tags_ui.route('/tag/taxonomies/tags/enabled/json')
@login_required
@login_read_only
def tag_taxonomies_tags_enabled_json():
    return jsonify(Tag.get_taxonomies_enabled_tags(r_list=True))

@tags_ui.route('/tag/galaxies/tags/enabled/json')
@login_required
@login_read_only
def tag_galaxies_tags_enabled_json():
    tags = Tag.get_galaxies_enabled_tags()
    return jsonify(Tag.get_tags_selector_dict(tags))

@tags_ui.route('/tag/custum/tags/enabled/json')
@login_required
@login_read_only
def tag_custum_tags_enabled_json():
    return jsonify(Tag.get_custom_enabled_tags(r_list=True))

@tags_ui.route('/tag/taxonomie/tags/enabled/json')
@login_required
@login_read_only
def tag_taxonomie_tags_enabled_json():
    taxonomie = request.args.get('taxonomie')
    return jsonify(Tag.get_taxonomie_enabled_tags(taxonomie, r_list=True))

@tags_ui.route('/tag/galaxy/tags/enabled/json')
@login_required
@login_read_only
def tag_galaxy_tags_enabled_json():
    galaxy = request.args.get('galaxy')
    tags = Tag.get_galaxy_enabled_tags(galaxy, r_list=True)
    return jsonify(Tag.get_tags_selector_dict(tags))

@tags_ui.route('/tag/search/item')
@login_required
@login_read_only
def tags_search_items():
    object_type = 'item'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    dict_tagged['date'] = Date.sanitise_date_range('', '', separator='-')
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/message')
@login_required
@login_read_only
def tags_search_messages():
    object_type = 'message'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    dict_tagged['date'] = Date.sanitise_date_range('', '', separator='-')
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/image')
@login_required
@login_read_only
def tags_search_images():
    object_type = 'image'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/ocr')
@login_required
@login_read_only
def tags_search_ocrs():
    object_type = 'ocr'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/qrcode')
@login_required
@login_read_only
def tags_search_qrcodes():
    object_type = 'qrcode'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}

var/www/templates/tags/block_tags_selector.html
<div class="input-group" >
  <input id="ltags" type="text" class="form-control" autocomplete="off" style="width: 760px" name="taxonomies_tags">
</div>

<div class="dropdown">
  <button type="button" class="btn btn-info dropdown-toggle mt-1 mb-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdown-taxonomie">
    Taxonomie Selected
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-taxonomie"> <!-- TODO: make dropdown-scrollable -->
    <h6 class="dropdown-header">Taxonomie Tags</h6>
    <button class="dropdown-item" type="button" id="all-tags-taxonomies">All Tags <i class="fas fa-tags"></i></button>
    <button class="dropdown-item" type="button" id="all-tags-customs">Custom Tags <i class="fas fa-tag"></i></button>
    <div class="dropdown-divider"></div>
    {% for taxo in tags_selector_data['active_taxonomies'] %}
      <button class="dropdown-item" type="button" id="{{ taxo }}-id{{ loop.index0 }}">{{ taxo }}</button>
    {% endfor %}
  </div>
</div>

<div class="input-group">
  <input id="ltagsgalaxies" type="text" class="form-control" autocomplete="off" style="width: 760px" name="galaxies_tags">
</div>

<div class="dropdown">
  <button type="button" class="btn btn-info dropdown-toggle mt-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdown-galaxy">
    Galaxy Selected
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-galaxy"> <!-- TODO: make dropdown-scrollable -->
    <h6 class="dropdown-header">Galaxy Tags</h6>
    <button class="dropdown-item" type="button" id="all-tags-galaxies">All Tags <i class="fas fa-tags"></i></button>
    <div class="dropdown-divider"></div>
    {% for galaxy in tags_selector_data['active_galaxies'] %}
      <button class="dropdown-item" type="button" id="{{ galaxy }}-idgalax{{ loop.index0 }}">{{ galaxy }}</button>
    {% endfor %}
  </div>
</div>



<!--
        <button class="btn btn-primary" onclick="tagsSelector()">
            <i class="fas fa-plus"></i>
            Add Tags
        </button>
 -->


<script>
var ltags;
var ltagsgalaxies;

$.getJSON("{{ url_for('tags_ui.get_all_taxonomies_customs_tags') }}",
    function(data) {
      {% if 'taxonomies_tags' in tags_selector_data %}
        var valueData = [
          {% for tag in tags_selector_data['taxonomies_tags'] %}
            '{{tag|safe}}',
          {%  endfor %}
        ];
      {% else %}
        var valueData = [];
      {% endif %}


      ltags = $('#ltags').tagSuggest({
        data: data,
        value: valueData,
        maxDropHeight: 200,
        name: 'ltags'
      });
    });

$.getJSON("{{ url_for('tags_ui.tag_galaxies_tags_enabled_json') }}",
  function(data) {
    {% if 'galaxies_tags' in tags_selector_data %}
      var valueData = [
        {% for tag in tags_selector_data['galaxies_tags'] %}
          '{{tag|safe}}',
        {%  endfor %}
      ];
    {% else %}
      var valueData = [];
    {% endif %}

    ltagsgalaxies = $('#ltagsgalaxies').tagSuggest({
      data: data,
      value: valueData,
      maxDropHeight: 200,
      name: 'ltagsgalaxies'
    });
  });

jQuery("#all-tags-taxonomies").click(function(e){
        //change input tags list
      $.getJSON("{{ url_for('tags_ui.get_all_taxonomies_customs_tags') }}",
        function(data) {
          ltags.setData(data)
      });
    });

jQuery("#all-tags-customs").click(function(e){
        //change input tags list
      $.getJSON("{{ url_for('tags_ui.tag_custum_tags_enabled_json') }}",
        function(data) {
          ltags.setData(data)
      });
    });

jQuery("#all-tags-galaxies").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_galaxies_tags_enabled_json') }}",
        function(data) {
          ltagsgalaxies.setData(data)
      });
    });

{% for taxo in tags_selector_data['active_taxonomies'] %}
    jQuery("#{{ taxo }}-id{{ loop.index0 }}").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_taxonomie_tags_enabled_json') }}?taxonomie={{ taxo }}",
        function(data) {
          ltags.setData(data)
  });
});
{% endfor %}

{% for galaxy in tags_selector_data['active_galaxies'] %}
    jQuery("#{{ galaxy }}-idgalax{{ loop.index0 }}").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_galaxy_tags_enabled_json') }}?galaxy={{ galaxy }}",
        function(data) {
          ltagsgalaxies.setData(data)
  });
});
{% endfor %}

// function tagsSelector() {
//   var tags = ltags.getValue()
//   var tagsgalaxy = ltagsgalaxies.getValue()
//   window.location.replace("myurl?tags=" + tags + "&tagsgalaxies=" + tagsgalaxy);
//}
</script>

var/www/templates/tags/galaxy_tag.html
<!DOCTYPE html>
<html>

<head>
  <title>Galaxy - AIL</title>
	<link rel="icon" href="{{ url_for('static', filename='image/ail-icon.png') }}">

  <!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap4.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

  <!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap4.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

</head>
<body>

  {% include 'nav_bar.html' %}

	<div class="container-fluid">
		<div class="row">

			{% include 'tags/menu_sidebar.html' %}

			<div class="col-12 col-lg-10" id="core_content">

                <div class="my-3">
                    <a href="{{ url_for('tags_ui.tags_galaxy') }}?galaxy={{ galaxy }}" class="pull-left">
                        <i class="fa fa-arrow-left fa"></i> {{ galaxy }} Galaxy
                    </a>
                </div>

                <div class="card">
                    <div class="card-header bg-secondary text-white">
                        <div class="d-flex">
                            <span class="h3">
                                {{ tag['value'] }}
                            </span>

                            <span class="h5 ml-auto">
                                {% if tag['enabled'] %}
                                    <span class="badge badge-success">Enabled</span>
                                {% else %}
                                    <span class="badge badge-danger">Disabled</span>
                                {% endif %}
                            </span>
                        </div>
                    </div>

                    <div class="card-body">
                        <h3><div class="mb-4">
                            <span class="badge badge-primary">{{ tag['tag'] }}</span>
                        </div></h3>
                        <table class="table table-sm table-hover">
                            <tbody>
                                {% if 'description' in tag %}
                                    <tr>
                                        <td><b>Description</b></td>
                                    <td>{{ tag['description'] }}</td>
                                    </tr>
                                {% endif %}
                                {% if 'refs' in tag %}
                                    <tr>
                                        <td><b>Refs</b></td>
                                        <td>{{ tag['refs'] }}</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>

                        {% if 'meta' in tag %}
                            <hr>
                            <b>Meta</b>
                            <pre class="border">{{ tag['meta'] }}</pre>
                        {% endif %}

{#                        <div class="mt-4">#}
{#                            {% if galaxy['enabled'] %}#}
{#                                <a href="{{ url_for('tags_ui.galaxy_disable') }}?galaxy={{ galaxy['type'] }}" class="btn btn-danger">#}
{#                                    <i class="fas fa-times"></i> Disable Galaxy#}
{#                                </a>#}
{#                            {% else %}#}
{#                                <a href="{{ url_for('tags_ui.galaxy_enable') }}?galaxy={{ galaxy['type'] }}" class="btn btn-success">#}
{#                                    <i class="fas fa-check"></i> Enable Galaxy#}
{#                                </a>#}
{#                            {% endif %}#}
{#                        </div>#}
                    </div>
                </div>

                <br><br><br><br>

    	    </div>
		</div>
	</div>

</body>

<script>
$(document).ready(function(){
    $("#navbar-tags").addClass("active");
    $("#nav_tags_config").removeClass("text-muted");

    table = $('#myTable_').DataTable(
        {
            "aLengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
            "iDisplayLength": 10,
            "order": [[ 3, "desc" ]]
        }
    );

});
</script>

<script>
function submitEnabledTags() {
    table.destroy();
	table = $('#myTable_').DataTable(
		{
			"iDisplayLength": -1,
		}
	);

function toggle_sidebar(){
	if($('#nav_menu').is(':visible')){
		$('#nav_menu').hide();
		$('#side_menu').removeClass('border-right')
		$('#side_menu').removeClass('col-lg-2')
		$('#core_content').removeClass('col-lg-10')
	}else{
		$('#nav_menu').show();
		$('#side_menu').addClass('border-right')
		$('#side_menu').addClass('col-lg-2')
		$('#core_content').addClass('col-lg-10')
	}
}

</script>


</html>

var/www/templates/tags/menu_sidebar.html
      <div class="col-12 col-lg-2 p-0 bg-light border-right" id="side_menu">

      	<button type="button" class="btn btn-outline-secondary mt-1 ml-3" onclick="toggle_sidebar()">
          <i class="fas fa-align-left"></i>
      	  <span>Toggle Sidebar</span>
      	</button>

      	<nav class="navbar navbar-expand navbar-light bg-light flex-md-column flex-row align-items-start py-2" id="nav_menu">
          <h5 class="d-flex text-muted w-100" id="nav_tags_search">
      		  <span>Tags Search</span>
      		</h5>
      	  <ul class="nav flex-md-column flex-row navbar-nav justify-content-between w-100">
      	    <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_items') }}" id="nav_tags_search_item">
      	        <i class="far fa-file"></i>
      	        Search Items by Tags
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_messages') }}" id="nav_tags_search_message">
      	        <i class="fas fa-comment-dots"></i>
      	        Search Messages by Tags
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_images') }}" id="nav_tags_search_image">
      	        <i class="fas fa-image"></i>
      	        Search Images by Tags
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_ocrs') }}" id="nav_tags_search_ocr">
      	        <i class="fas fa-expand"></i>
      	        Search Ocrs by Tags
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_qrcodes') }}" id="nav_tags_search_qrcode">
      	        <i class="fas fa-qrcode"></i>
      	        Search Qrcodes by Tags
      	      </a>
      	    </li>
      	    <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_domains') }}" id="nav_tags_search_domain">
      					<i class="fab fa-html5"></i>
      	       	Search Domains by Tags
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_decoded') }}" id="nav_tags_search_decoded">
      					<i class="fas fa-lock-open"></i>
      	       	Search Decoded Items by Tags
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_search_screenshot') }}" id="nav_tags_search_screenshot">
      					<i class="fas fa-image"></i>
      	       	Search Screenshots by Tags
      	      </a>
      	    </li>
          </ul>
            <h5 class="d-flex text-muted w-100" id="nav_tags_config">
      		  <span>Tags Management </span>
      		</h5>
      	  <ul class="nav flex-md-column flex-row navbar-nav justify-content-between w-100">
      	    <li class="nav-item">
      	      <a class="nav-link" href="{{ url_for('tags_ui.tags_taxonomies') }}" id="nav_taxonomies">
      	        <i class="fas fa-tags"></i>
      	        Taxonomies
      	      </a>
      	    </li>
      	    <li class="nav-item">
                <a class="nav-link" href="{{ url_for('tags_ui.tags_galaxies') }}" id="nav_galaxies">
                    <i class="fas fa-rocket"></i>
                    Galaxies
                </a>
      	    </li>
          </ul>
          <h5 class="d-flex text-muted w-100" id="nav_tags_export">
      		  <span>Tags Export </span>
      		</h5>
          <ul class="nav flex-md-column flex-row navbar-nav justify-content-between w-100">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('tags_ui.auto_push')}}" id="nav_auto_push">
                <i class="fas fa-cogs"></i>
                MISP and Hive, auto push
              </a>
            </li>
          </ul>
          <h5 class="d-flex text-muted w-100" id="nav_quick_search">
      		  <span>Quick Search </span>
      		</h5>
          <ul class="nav flex-md-column flex-row navbar-nav justify-content-between w-100">
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="credential"' id='nav_tag_infoleakautomatic-detectioncredential'>
                <i class="fas fa-unlock-alt"></i>
                Credentials
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="credit-card"' id='nav_tag_infoleakautomatic-detectioncredit-card'>
                <i class="far fa-credit-card"></i>
                Credit cards
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="mail"' id='nav_tag_infoleakautomatic-detectionmail'>
                <i class="fas fa-envelope"></i>
                Mails
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="cve"' id='nav_tag_infoleakautomatic-detectioncve'>
                <i class="fas fa-bug"></i>
                CVEs
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="onion"' id='nav_tag_infoleakautomatic-detectiononion'>
                <i class="fas fa-user-secret"></i>
                Onions
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="bitcoin-address"' id='nav_tag_infoleakautomatic-detectionbitcoin-address'>
                <i class="fab fa-bitcoin"></i>
                Bitcoin
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="base64"' id='nav_tag_infoleakautomatic-detectionbase64'>
                <i class="fas fa-lock-open"></i>
                Base64
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{{url_for('tags_ui.get_obj_by_tags')}}?object_type=item&ltags=infoleak:automatic-detection="phone-number"' id='nav_tag_infoleakautomatic-detectionphone-number'>
                <i class="fas fa-phone"></i>
                Phones
              </a>
            </li>
          </ul>
      	</nav>
      </div>